# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which sets up periodic OSV-Scanner scanning for vulnerabilities,
# in addition to a PR check which fails if new vulnerabilities are introduced.
#
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://google.github.io/osv-scanner/github-action/

name: OSV-Scanner

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  schedule:
    - cron: '42 19 * * 1'
  push:
    branches: [ "main" ]

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  setup-go-and-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Go using the version specified in the go.mod file
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'

      # Install Go dependencies based on go.mod
      - name: Install dependencies
        run: go mod download

      # Manually download and run OSV-Scanner for scheduled jobs
      - name: Download and Run OSV-Scanner (scheduled)
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        run: |
          ARCH=$(uname -m)
          if [[ "$ARCH" == "x86_64" ]]; then
            curl -sSL https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64 -o osv-scanner
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi
          chmod +x osv-scanner
          ./osv-scanner --recursive --skip-git ./


      # Manually download and run OSV-Scanner for PRs
      - name: Run OSV-Scanner (PR)
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
        run: |
          ARCH=$(uname -m)
          if [[ "$ARCH" == "x86_64" ]]; then
            curl -sSL https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64 -o osv-scanner
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi
          chmod +x osv-scanner
          ./osv-scanner --recursive --skip-git ./

      # Run Dependency Review Action to ensure that dependency versions are safe and properly encoded
      - name: Run dependency review action
        uses: actions/dependency-review-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # Allows the action to continue even if it fails, so we can debug it later

      # Debug output for the dependency review action if it fails
      - name: Debug Dependency Review Output
        if: failure()
        run: cat dependency-review-results.json
