# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which sets up periodic OSV-Scanner scanning for vulnerabilities,
# in addition to a PR check which fails if new vulnerabilities are introduced.
#
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://google.github.io/osv-scanner/github-action/

name: OSV-Scanner

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  schedule:
    - cron: '42 19 * * 1'
  push:
    branches: [ "main" ]

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  setup-go-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'

      - name: Install dependencies
        run: go mod download

      - name: Run OSV-Scanner (scheduled)
        if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        run: |
          curl -sSL https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64 -o osv-scanner
          chmod +x osv-scanner
          ./osv-scanner --recursive --skip-git ./

      - name: Run OSV-Scanner (PR)
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
        run: |
          curl -sSL https://github.com/google/osv-scanner/releases/latest/download/osv-scanner-linux-amd64 -o osv-scanner
          chmod +x osv-scanner
          ./osv-scanner --recursive --skip-git ./
